# Generated by Django 3.0.5 on 2020-04-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200423_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='storage_location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
