# Generated by Django 3.0.5 on 2020-04-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200426_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rfid',
            field=models.CharField(error_messages={'unique': 'The RFID already exists'}, max_length=50, unique=True),
        ),
    ]
